import type { InlineCode, Paragraph, PhrasingContent, Strong, Text } from "mdast";
import type { FormatterConfig } from "../config.js";
import type { InlineMath, VisitorRegistry } from "./registry.js";
import {
    endsWithWhitespace,
    getAutoGeneratedLeafValue,
    InlineNodeType,
    isAutoGeneratedNode,
    makeGeneratedData,
    renderLiteralInline,
    replaceInlineNodesInParagraph,
    startsWithWhitespace,
    wrapWordsInParagraph,
} from "./utils.js";

type InlineHandleMode = FormatterConfig["inline"]["handleInlineCode"];

interface InlineRunMergeSpec {
    wrappedNodeType: InlineNodeType;
    buildMergedNode: (run: PhrasingContent[]) => PhrasingContent;
}

function mergeGeneratedRunsInParagraph(node: Paragraph, spec: InlineRunMergeSpec): void {
    const children = node.children as PhrasingContent[];
    const merged: PhrasingContent[] = [];

    let i = 0;
    while (i < children.length) {
        const current = children[i];
        if (!isAutoGeneratedNode(current, spec.wrappedNodeType)) {
            merged.push(current);
            i += 1;
            continue;
        }

        const run: PhrasingContent[] = [current];
        let j = i + 1;
        while (j < children.length) {
            const prev = run[run.length - 1];
            const next = children[j];
            const joinableType = next.type === "emphasis" || isAutoGeneratedNode(next, spec.wrappedNodeType);
            if (!joinableType || endsWithWhitespace(prev) || startsWithWhitespace(next)) {
                break;
            }
            run.push(next);
            j += 1;
        }

        if (run.length > 1) {
            merged.push(spec.buildMergedNode(run));
            i = j;
            continue;
        }

        merged.push(current);
        i += 1;
    }

    node.children = merged as typeof node.children;
}

function buildMergedStrongNode(run: PhrasingContent[]): Strong {
    const strongChildren: PhrasingContent[] = [];
    for (const part of run) {
        if (part.type === "strong" && isAutoGeneratedNode(part, "strong")) {
            strongChildren.push(...(part.children as PhrasingContent[]));
        } else {
            strongChildren.push(part);
        }
    }
    return { type: "strong", children: strongChildren } as Strong;
}

function buildMergedLeafNode(nodeType: "inlineCode" | "inlineMath", run: PhrasingContent[]): PhrasingContent {
    const value = run.map((part) =>
        isAutoGeneratedNode(part, nodeType)
            ? getAutoGeneratedLeafValue(part)
            : renderLiteralInline(part)
    ).join("");

    return nodeType === "inlineCode"
        ? ({ type: "inlineCode", value } as InlineCode)
        : ({ type: "inlineMath", value } as InlineMath);
}

interface InlineParagraphHandlerSpec {
    handleMode: InlineHandleMode;
    wrappedNodeType: InlineNodeType;
    wrapWord: (word: string) => PhrasingContent;
    unwrapChild: (child: PhrasingContent) => PhrasingContent[];
    postProcess?: (node: Paragraph) => void;
}

function registerInlineParagraphHandler(
    registry: VisitorRegistry,
    spec: InlineParagraphHandlerSpec,
): void {
    if (spec.handleMode === "removeAll") {
        registry.paragraph.push((node: Paragraph) => {
            replaceInlineNodesInParagraph(node, (child) => spec.unwrapChild(child));
        });
        return;
    }

    if (spec.handleMode === "allEnglishWord") {
        registry.paragraph.push((node: Paragraph) => {
            wrapWordsInParagraph(node, spec.wrapWord, "mathSegment", true, spec.wrappedNodeType);
            spec.postProcess?.(node);
        });
    }
}

/**
 * 根据 config.inline 处理 InlineCode / Strong / InlineMath 节点。
 *
 * 基础行为（写死，始终执行）：
 *   - 去除 inlineCode / inlineMath 的首尾空格（value.trim()）
 *   - 去除 strong 第一 / 最后一个 Text 子节点的首尾空格
 *   - emphasis/strong 的 `_`/`*` 由原始文本定义，不强制转换
 *
 * handleInlineCode / handleInlineMath / handleInlineStrong（段落级别操作）：
 *   - 'normal'     : 仅做基础处理
 *   - 'removeAll'  : 移除所有对应行内标记（保留文本内容）
 *   - 'allEnglishWord' : 将段落 Text 节点中的英文单词包裹为对应行内节点
 *
 * 注意：段落级操作注册在 registry.paragraph，应在 wordSpacing 之前执行（见 index.ts）。
 */
export function registerInlineFormatting(registry: VisitorRegistry, config: FormatterConfig): void {
    const { handleInlineCode, handleInlineMath, handleInlineStrong } = config.inline;

    // ── 基础行为：去除首尾空格 ─────────────────────────────────────────────
    registry.inlineCode.push((node: InlineCode) => {
        // node.value = node.value.trim(); // 代码还是保留完整吧
    });

    registry.inlineMath.push((node: InlineMath) => {
        node.value = node.value.trim();
    });

    registry.strong.push((node: Strong) => {
        if (node.children.length === 0) return;
        const first = node.children[0];
        if (first.type === "text") (first as Text).value = (first as Text).value.trimStart();
        const last = node.children[node.children.length - 1];
        if (last.type === "text") (last as Text).value = (last as Text).value.trimEnd();
    });

    registerInlineParagraphHandler(registry, {
        handleMode: handleInlineCode,
        wrappedNodeType: "inlineCode",
        wrapWord: (word) => ({ type: "inlineCode", value: word, data: makeGeneratedData() }) as InlineCode,
        unwrapChild: (child) => child.type === "inlineCode"
            ? [{ type: "text", value: (child as InlineCode).value } as Text]
            : [child],
        postProcess: (node) => mergeGeneratedRunsInParagraph(node, {
            wrappedNodeType: "inlineCode",
            buildMergedNode: (run) => buildMergedLeafNode("inlineCode", run),
        }),
    });

    registerInlineParagraphHandler(registry, {
        handleMode: handleInlineMath,
        wrappedNodeType: "inlineMath",
        wrapWord: (word) => ({ type: "inlineMath", value: word, data: makeGeneratedData() }) as InlineMath,
        unwrapChild: (child) => child.type === "inlineMath"
            ? [{ type: "text", value: (child as InlineMath).value } as Text]
            : [child],
        postProcess: (node) => mergeGeneratedRunsInParagraph(node, {
            wrappedNodeType: "inlineMath",
            buildMergedNode: (run) => buildMergedLeafNode("inlineMath", run),
        }),
    });

    registerInlineParagraphHandler(registry, {
        handleMode: handleInlineStrong,
        wrappedNodeType: "strong",
        wrapWord: (word) => ({
            type: "strong",
            children: [{ type: "text", value: word } as Text],
            data: makeGeneratedData(),
        }) as Strong,
        unwrapChild: (child) => child.type === "strong"
            ? [...((child as Strong).children as PhrasingContent[])]
            : [child],
        postProcess: (node) => mergeGeneratedRunsInParagraph(node, {
            wrappedNodeType: "strong",
            buildMergedNode: (run) => buildMergedStrongNode(run),
        }),
    });
}
