import type { InlineCode, Paragraph, PhrasingContent, Text } from "mdast";
import type { InlineMath } from "./registry.js";

/** 循环去除 value 末尾出现的任意指定字符串（可重复去除，直到无变化为止）。 */
export function trimTrailingChars(value: string, chars: string[]): string {
    let changed = true;
    while (changed) {
        changed = false;
        for (const ch of chars) {
            if (value.endsWith(ch)) {
                value = value.slice(0, -ch.length);
                changed = true;
            }
        }
    }
    return value;
}

export type InlineNodeType = "inlineCode" | "inlineMath" | "strong";
export type AutoGeneratedData = { generatedByAllEnglishWord?: true };

/** 将字符串按连续英文字母序列拆分为 {isWord, value} 片段数组。 */
export function splitByEnglishWords(
    text: string,
    mode: "token" | "mathSegment" = "token",
): Array<{ isWord: boolean; value: string }> {
    const result: Array<{ isWord: boolean; value: string }> = [];
    const asciiToken = "[!\"#$%&'()*+,\\-./:;<=>?@[\\\\\\]^_`{|}~A-Za-z0-9]+";
    const pattern = mode === "mathSegment"
        ? `(${asciiToken}(?:[^\\S\\r\\n]+${asciiToken})*)`
        : `(${asciiToken})`;
    const re = new RegExp(pattern, "g");
    let lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = re.exec(text)) !== null) {
        if (match.index > lastIndex) {
            result.push({ isWord: false, value: text.slice(lastIndex, match.index) });
        }
        result.push({ isWord: true, value: match[0] });
        lastIndex = match.index + match[0].length;
    }
    if (lastIndex < text.length) {
        result.push({ isWord: false, value: text.slice(lastIndex) });
    }
    return result;
}

export function wrapWordsInParagraph(
    node: Paragraph,
    wrapWord: (word: string) => PhrasingContent,
    mode: "token" | "mathSegment" = "token",
    normalizeBoundarySpaces = false,
    wrappedNodeType?: PhrasingContent["type"],
): void {
    const newChildren: PhrasingContent[] = [];
    for (const child of node.children) {
        if (child.type === "text") {
            for (const part of splitByEnglishWords((child as Text).value, mode)) {
                if (part.isWord) {
                    newChildren.push(wrapWord(part.value));
                } else if (part.value) {
                    newChildren.push({ type: "text", value: part.value } as Text);
                }
            }
        } else {
            newChildren.push(child);
        }
    }

    if (normalizeBoundarySpaces) {
        for (let i = 0; i < newChildren.length; i++) {
            const child = newChildren[i];
            if (child.type !== "text") continue;

            const prev = i > 0 ? newChildren[i - 1] : undefined;
            const next = i + 1 < newChildren.length ? newChildren[i + 1] : undefined;
            let value = (child as Text).value;

            if (wrappedNodeType !== undefined && prev?.type === wrappedNodeType) {
                value = value.replace(/^[^\S\r\n]+/, " ");
            }
            if (wrappedNodeType !== undefined && next?.type === wrappedNodeType) {
                value = value.replace(/[^\S\r\n]+$/, " ");
            }
            (child as Text).value = value;
        }
    }

    node.children = newChildren as typeof node.children;
}

export function isAutoGeneratedNode(node: PhrasingContent, nodeType: InlineNodeType): boolean {
    return node.type === nodeType && (node as PhrasingContent & { data?: AutoGeneratedData }).data?.generatedByAllEnglishWord === true;
}

export function makeGeneratedData(): AutoGeneratedData {
    return { generatedByAllEnglishWord: true };
}

export function startsWithWhitespace(node: PhrasingContent): boolean {
    if (node.type === "text") return /^\s/.test((node as Text).value);
    if (node.type === "inlineCode") return /^\s/.test((node as InlineCode).value);
    if (node.type === "inlineMath") return /^\s/.test((node as InlineMath).value);
    if (node.type === "strong" || node.type === "emphasis") {
        const first = node.children[0] as PhrasingContent | undefined;
        return first ? startsWithWhitespace(first) : false;
    }
    return false;
}

export function endsWithWhitespace(node: PhrasingContent): boolean {
    if (node.type === "text") return /\s$/.test((node as Text).value);
    if (node.type === "inlineCode") return /\s$/.test((node as InlineCode).value);
    if (node.type === "inlineMath") return /\s$/.test((node as InlineMath).value);
    if (node.type === "strong" || node.type === "emphasis") {
        const last = node.children[node.children.length - 1] as PhrasingContent | undefined;
        return last ? endsWithWhitespace(last) : false;
    }
    return false;
}

export function renderLiteralInline(node: PhrasingContent): string {
    if (node.type === "text") return (node as Text).value;
    if (node.type === "inlineCode") return "`" + (node as InlineCode).value + "`";
    if (node.type === "inlineMath") {
        const marker = ((node as InlineMath & { data?: { marker?: string } }).data?.marker ?? "$");
        return marker + (node as InlineMath).value + marker;
    }
    if (node.type === "emphasis") {
        const marker = ((node as { data?: { marker?: string } }).data?.marker ?? "*");
        return marker + node.children.map((child) => renderLiteralInline(child as PhrasingContent)).join("") + marker;
    }
    if (node.type === "strong") {
        const marker = ((node as { data?: { marker?: string } }).data?.marker ?? "*").repeat(2);
        return marker + node.children.map((child) => renderLiteralInline(child as PhrasingContent)).join("") + marker;
    }
    return "";
}

export function getAutoGeneratedLeafValue(node: PhrasingContent): string {
    if (node.type === "inlineCode") return (node as InlineCode).value;
    if (node.type === "inlineMath") return (node as InlineMath).value;
    return renderLiteralInline(node);
}

export function replaceInlineNodesInParagraph(
    node: Paragraph,
    replaceChild: (child: PhrasingContent) => PhrasingContent[],
): void {
    node.children = (node.children as PhrasingContent[]).flatMap(replaceChild) as typeof node.children;
}
